export const FETCH_IMAGES= 'FETCH_IMAGES';
export const FETCH_MODAL_IMAGE= 'FETCH_MODAL_IMAGE';
export const CLOSE_MODAL_WINDOW= 'CLOSE_MODAL_WINDOW';
export const ADD_COMMENT= 'ADD_COMMENT';
export const FETCH_MODAL_IMAGE_ERROR='FETCH_MODAL_IMAGE_ERROR'